# Generated by Django 4.2.4 on 2023-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
