# Generated by Django 4.2.4 on 2023-08-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portinfo', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
