# Generated by Django 4.1 on 2023-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portinfo', '0003_article_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
